depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: data/Tanks
  scene: ['Church']
  customized_focal: False
  random_ref: 4
training:
  out_dir:  out/Tanks/Church
  auto_scheduler: True
extract_images:
  resolution: [540, 960]